import { Input, Textarea } from '@/ui'

import { Section } from '../shared/Section'
import { Field } from '../shared/Field'
import { Toggle } from '../shared/Toggle'

type Props = {
  form: {
    signatureEnabled: boolean
    setSignatureEnabled: (v: boolean) => void

    stripAI: boolean
    setStripAI: (v: boolean) => void

    template: string
    setTemplate: (v: string) => void

    company: string
    setCompany: (v: string) => void

    email: string
    setEmail: (v: string) => void

    website: string
    setWebsite: (v: string) => void
  }
}

export function SignatureSection({ form }: Props) {
  const templateError =
    form.signatureEnabled && !form.template.trim()

  const handleSignatureToggle = (value: boolean) => {
    form.setSignatureEnabled(value)

    if (!value) {
      form.setStripAI(true)
    }
  }

  return (
    <Section
      title="Signature"
      description="Customize how AI-generated messages are signed and presented."
    >
      {/* Enable Signature */}
      <Toggle
        label="Enable Signature"
        description="Append a signature to all AI-generated replies."
        checked={form.signatureEnabled}
        onChange={handleSignatureToggle}
      />

      {/* Strip AI Label */}
      <Toggle
        label="Remove AI Label"
        description="Remove any indication that the message was generated by AI."
        checked={form.stripAI}
        onChange={form.setStripAI}
        disabled={!form.signatureEnabled}
      />

      {/* Compliance Notice */}
      {form.stripAI && form.signatureEnabled && (
        <div className="mt-2 rounded-md border border-yellow-300 bg-yellow-50 p-3 text-sm text-yellow-800">
          ⚠️ Transparency Notice: In some regions and industries, users must be informed
          when they are interacting with AI-generated responses.
        </div>
      )}

      {/* Only show fields if enabled */}
      {form.signatureEnabled && (
        <>
          <Field
            label="Signature Template"
            description="Example: Regards, {{company}}"
            error={
              templateError
                ? 'Template is required when signature is enabled'
                : undefined
            }
          >
            <Textarea
              value={form.template}
              onChange={(e) => form.setTemplate(e.target.value)}
              placeholder="Regards, {{company}}"
            />
          </Field>

          <Field label="Company Name">
            <Input
              value={form.company}
              onChange={(e) => form.setCompany(e.target.value)}
              placeholder="Your company"
            />
          </Field>

          <Field label="Support Email">
            <Input
              value={form.email}
              onChange={(e) => form.setEmail(e.target.value)}
              placeholder="support@example.com"
            />
          </Field>

          <Field label="Website">
            <Input
              value={form.website}
              onChange={(e) => form.setWebsite(e.target.value)}
              placeholder="https://yourwebsite.com"
            />
          </Field>
        </>
      )}
    </Section>
  )
}